### ISSUE TITLE
How to prepare SBD(or VOC2012) dataset

### ISSUE THREAD

**Issue by zhangxiaosong18** [holyseven/PSPNet-TF-Reproduce#12]
hi, I found that this code supports SBD and Cityscapes dataset, but did not explain how to prepare SBD dataset, can you tell me? thank you.

**Comment by holyseven** [comment]
change the [find_data_path](https://github.com/holyseven/PSPNet-TF-Reproduce/blob/master/database/reader_segmentation.py#L359) fucntion. I have [some files here](https://github.com/holyseven/PSPNet-TF-Reproduce/tree/master/database/SBD_data_path) or you can do it by yourself.

**Comment by holyseven** [comment]
I just noticed that it is difficult to find it online so I put the dataset on google drive for convenient use (around 1.5~1.6G) 

https://drive.google.com/open?id=19gjw9qBHVrsuoLt_F1Svuu6wxiR4UHsr
md5: 9fac86066b14fd6234c8853e8d3800ed
