### ISSUE TITLE
Have you ever tested other variants of the L2-SP?

### ISSUE THREAD

**Issue by fanq15** [holyseven/PSPNet-TF-Reproduce#2]
Thanks!

**Comment by holyseven** [comment]
We have tested other variants (L2-SP-Fisher, L1-SP, GL-SP, GL-SP-Fisher) on classification tasks, see the [paper](https://arxiv.org/abs/1802.01483) for details. The conclusion is that L2-SP is the most efficient. 

As for segmentation tasks, we have only evaluated L2-SP.

**Comment by fanq15** [comment]
BTW, I think your code is great! Maybe you could

**Comment by PkuRainBow** [comment]
I am wondering the influence of the L2-SP compared with the basic weight decay.

It would be great if you could provide the exact performance.

**Comment by fanq15** [comment]
Same as his. I forget the exact performance, but I can make sure the difference is minor. https://github.com/holyseven/PSPNet-TF-Reproduce/issues/1

**Comment by PkuRainBow** [comment]
@fanq15 Could you share your peformance with the L2-SP and the original weight day.
