### ISSUE TITLE
predict

### ISSUE THREAD

**Issue by AmberHen** [holyseven/PSPNet-TF-Reproduce#22]
1. when ms=1,mirror = 0
np.unique（total_proba）
[ 0.48855963  0.48895204  0.48936412 ... 16.93312    16.933477
 16.93356   ]
shape:total_proba
(512, 512, 2)
prediction.shape
(512, 512)
np.unique(prediction)
[0]
2. when ms=1,mirror=1
unique:total_proba
[ 0.99463326  0.9946749   0.9948443  ... 33.892696   33.892704
 33.892773  ]
shape:total_proba
(512, 512, 2)
prediction.shape
(512, 512)
unique(prediction)
[0]
Why are the predicted values 0? Thanks!

**Comment by holyseven** [comment]
when training, loss function and miou are normal?
