### ISSUE TITLE
trained model?

### ISSUE THREAD

**Issue by lilyswang** [holyseven/PSPNet-TF-Reproduce#29]
Hi , @holyseven ,thanks for your nice job about PSPNET. I am a beginner of   Semantic segmentation.  I try to train the model but it is so slow. :(
Could you provide a well trained pspnet 50 model?   Thanks a lot.

**Comment by holyseven** [comment]
Hello @lilyswang 
If you want a trained model, the authors of PSPNet have already proposed several choices, see https://github.com/hszhao/PSPNet#usage. 

I have no access to my trained models at this moment. Sad story :(

**Comment by holyseven** [comment]
To get a trained model for segmentation in Pytorch, you can see here: https://hangzhang.org/PyTorch-Encoding/model_zoo/segmentation.html.
