### ISSUE TITLE
I guess there is one extra line in the function of inference of pspnet

### ISSUE THREAD

**Issue by xiongzhanblake** [holyseven/PSPNet-TF-Reproduce#3]
https://github.com/holyseven/PSPNet-TF-Reproduce/blob/396a8a5c2855a25ed59efd9c7ab9b956cfb21ec2/model/pspnet_mg.py#L196

**Comment by holyseven** [comment]
`avg_pool` has `ksize` and `strides` arguments, which are set to the same, i.e. `utils.stride_arr(pool_size[pool_index], self.data_format)`.

**Comment by xiongzhanblake** [comment]
Thanks for your reply! I found its definition in utils.py. 
By the way, have you used dense_crf as the post-process at the end?

**Comment by holyseven** [comment]
Tried (use `pip` to install the library), but it takes a lot of time and does not improve the performance. There are some h-parameters to configure, I tried only the default values, maybe they are not good for Cityscapes.

**Comment by xiongzhanblake** [comment]
I did not find dense_crf layer in original pspnet as well. I will skip it for now. Thanks for your advice.
