### ISSUE TITLE
请问显存不够问题怎么解决

### ISSUE THREAD

**Issue by dgliu123** [holyseven/PSPNet-TF-Reproduce#30]
我目前机器是两个1080的显卡  每个卡12G显存,batch设置成了1 
跑起来后就出现显存不够问题

**Comment by holyseven** [comment]
image_size 调小一些？`nvidia-smi`看看是否有其它程序占用GPU内存。这个repo也没有实现freeze_bn的功能，所以建议batch size 能大于8。

如果想复现PSPNet，可以参考作者的Pytorch实现：https://github.com/hszhao/semseg
