### ISSUE TITLE
My performance is lower than your report on VOC dataset

### ISSUE THREAD

**Issue by fanq15** [holyseven/PSPNet-TF-Reproduce#5]
I use the same setups as your document, but my performance is lower than your report on VOC dataset.
When I train with only train set (10582 images), tested on val set (1449), L2 got 76.6, L2-SP 78.4.
I am very curious about the reason.
Thanks!

**Comment by holyseven** [comment]
Have you tested with multi-scale (ms)? with the script like this:

`CUDA_VISIBLE_DEVICES=0 python ./predict.py --server $s --database 'SBD' --structure_in_paper 0 --save_prediction 1 --color_switch 0 --test_image_size 480 --mode 'test' --weights_ckpt './log/SBD/only-resnet-1/snapshot/model.ckpt-30000' --coloring 0 --mirror 1 --ms 1`

**EDITED** for evaluation on the validation set:
`CUDA_VISIBLE_DEVICES=0 python ./predict.py --server $s --database 'SBD' --structure_in_paper 0 --save_prediction 0 --color_switch 0 --test_image_size 480 --mode 'val' --weights_ckpt './log/SBD/only-resnet-1/snapshot/model.ckpt-30000' --coloring 0 --mirror 1 --ms 1`

**Comment by fanq15** [comment]
Nope... I will try it. Thank you very much!
