### ISSUE TITLE
Have you trained the model based on instance level label?

### ISSUE THREAD

**Issue by irfanICMLL** [holyseven/PSPNet-TF-Reproduce#6]
In the readme, it shows that the id should be generated by createTrainIdInstanceImgs.py . But why we use this label for training? We just want to do a semantic segmentation, not a instance segmentation? Will use the instance label help to increase the mIOU?

**Comment by holyseven** [comment]
Oops... the pointer should be [createTrainIdLabelImgs.py](https://github.com/mcordts/cityscapesScripts/blob/master/cityscapesscripts/preparation/createTrainIdLabelImgs.py). Sorry for that confusion.

**Comment by irfanICMLL** [comment]
Thank you for your reply~
