### ISSUE TITLE
How to use the coarse data properly?

### ISSUE THREAD

**Issue by PkuRainBow** [holyseven/PSPNet-TF-Reproduce#8]
Hi, really great work.

I noticed that you got about 1 point performance improvement by using the coarse labeled data and the original PSPNet reported that they got 2 points improvements.

However, I always failed to improve the performance by using the coarse labeled data...... Which is very strange .......... 

I am wondering whether anyone also meet similar problem. I am using the Pytorch as the framework.

**Comment by holyseven** [comment]
see #4.
