### ISSUE TITLE
structure_in_paper

### ISSUE THREAD

**Issue by FengLoveBella** [holyseven/PSPNet-TF-Reproduce#9]
Hi @holyseven, nice work. I have a problem when using 'structure_in_paper' setting in your released paper, because of the initial model ResNet_v1_101 is different to the code in structure_in_paper. Could you share the initial resnet101 model which can be used in the 'structure_in_paper' mode? Thank you very much!

**Comment by holyseven** [comment]
I have no such initial model. Discussion with the author of PSPNet: 

>  For the beginning blocks of ResNet, the original implementation use kernel size as 7 while we use 3, these two both use stride as 2 to downsize the input size as half of the original input image for faster training. It does not make much difference regards the final accuracy, while kernel size as 3 is faster than 7 for training.

There are some trained models from https://github.com/hszhao/PSPNet, but on ADE, VOC or Cityscapes.

**Comment by FengLoveBella** [comment]
@holyseven Thank you very much. And another question, did you try class weight in your code? does it help? (Because the classes are inbalance)

**Comment by holyseven** [comment]
[FCN](https://people.eecs.berkeley.edu/~jonlong/long_shelhamer_fcn.pdf) tried to do the class balancing on VOC but found unnecessary.

> Although our labels are mildly unbalanced (about 3/4 are background), we find class balancing  unnecessary.

I tried the simplest (giving each class a weight, the inverse of pixel number rate) and [focal loss with gamma=2](https://github.com/holyseven/PSPNet-TF-Reproduce/blob/master/model/pspnet_mg.py#L262), but found no help. **Maybe** more hyper-parameter tuning or more advanced techniques will help.

**Comment by FengLoveBella** [comment]
@holyseven OK, I got it, 3ks.
